name: deploy

on:
  push:
    branches:
      - main

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: |
          echo keyPassword=\${{secrets.KEY_PASSWORD}} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_STORE_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.ALIAS }} >> ${{env.PROPERTIES_PATH}}

      - run: echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > android/app/key.jks

      - run: |
          flutter pub get
          flutter build appbundle

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed appbundle
          path: build/app/outputs/bundle/release/app-release.aab
